import reports

with open('report.txt', "w") as file:
    file.write(str(reports.count_games('game_stat.txt')))
    file.write('\n\n')
    file.write(str(reports.decide('game_stat.txt', int(input('Input a year: ')))))
    file.write('\n\n')
    file.write(str(reports.get_latest('game_stat.txt')))
    file.write('\n\n')
    file.write(str(reports.count_by_genre('game_stat.txt', input('Input a genre: '))))
    file.write('\n\n')
    file.write(str(reports.get_line_number_by_title('game_stat.txt', input('Input a title: '))))
    file.write('\n\n')
    file.write(str(reports.sort_abc('game_stat.txt')))
    file.write('\n\n')
    file.write(str(reports.get_genres('game_stat.txt')))
    file.write('\n\n')
    file.write(str(reports.get_most_played('game_stat.txt')))
    file.write('\n\n')
    file.write(str(reports.sum_sold('game_stat.txt')))
    file.write('\n\n')
    file.write(str(reports.get_selling_avg('game_stat.txt')))
    file.write('\n\n')
    file.write(str(reports.count_longest_title('game_stat.txt')))
    file.write('\n\n')
    file.write(str(reports.get_date_avg('game_stat.txt')))
    file.write('\n\n')
    file.write(str(reports.get_game('game_stat.txt', input('Input a title: '))))
    file.write('\n\n')