import reports

print('Friendly output of every function:', '\n')
print('Total count games')
print(reports.count_games('game_stat.txt'), '\n')
print('Decision')
print(reports.decide('game_stat.txt', int(input('Input a year: '))), '\n')
print('Latest game is:')
print(reports.get_latest('game_stat.txt'), '\n')
print('Number of games counted by input genre')
print(reports.count_by_genre('game_stat.txt', input('Input a genre: ')),'\n')
print('Find line of input title')
print(reports.get_line_number_by_title('game_stat.txt', input('Input a title: ')), '\n')
print('Alphabetical sort')
print(reports.sort_abc('game_stat.txt'), '\n')
print('Genres list')
print(reports.get_genres('game_stat.txt'), '\n')
print('Most played game is:')
print(reports.get_most_played('game_stat.txt'), '\n')
print('Total games sold:')
print(reports.sum_sold('game_stat.txt'), '\n')
print('Average selling is:')
print(reports.get_selling_avg('game_stat.txt'), '\n')
print('Input title to see list of all properties of the game')
print(reports.get_game('game_stat.txt', input('Input of a title: ')), '\n')
print('Numbers of characters in longest title')
print(reports.count_longest_title('game_stat.txt'), '\n')
print('Average release date is')
print(reports.get_date_avg('game_stat.txt'), '\n')